name: Valid JSON

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Swift-Sh
      run: brew install mxcl/made/swift-sh
    - name: Select Xcode 11.4
      run: sudo xcode-select -s /Applications/Xcode_11.4.app && xcodebuild -version
    - name: Validate JSON
      run: swift sh validate.swift diff
